export const PERMISSIONS = {
  // User Management
  USERS_VIEW: "users.view",
  USERS_CREATE: "users.create",
  USERS_EDIT: "users.edit",
  USERS_DELETE: "users.delete",

  // Role Management
  ROLES_VIEW: "roles.view",
  ROLES_CREATE: "roles.create",
  ROLES_EDIT: "roles.edit",
  ROLES_DELETE: "roles.delete",

  // Product Management
  PRODUCTS_VIEW: "products.view",
  PRODUCTS_CREATE: "products.create",
  PRODUCTS_EDIT: "products.edit",
  PRODUCTS_DELETE: "products.delete",
  PRODUCTS_MANAGE_STOCK: "products.manage_stock",

  // Order Management
  ORDERS_VIEW: "orders.view",
  ORDERS_CREATE: "orders.create",
  ORDERS_EDIT: "orders.edit",
  ORDERS_DELETE: "orders.delete",
  ORDERS_REFUND: "orders.refund",

  // Customer Management
  CUSTOMERS_VIEW: "customers.view",
  CUSTOMERS_CREATE: "customers.create",
  CUSTOMERS_EDIT: "customers.edit",
  CUSTOMERS_DELETE: "customers.delete",

  // Inventory Management
  INVENTORY_VIEW: "inventory.view",
  INVENTORY_ADJUST: "inventory.adjust",
  INVENTORY_RECEIVE: "inventory.receive",
  INVENTORY_CHECK: "inventory.check",

  // Reports
  REPORTS_VIEW: "reports.view",
  REPORTS_EXPORT: "reports.export",
  REPORTS_FINANCIAL: "reports.financial",

  // Settings
  SETTINGS_VIEW: "settings.view",
  SETTINGS_EDIT: "settings.edit",
  SETTINGS_SYSTEM: "settings.system",

  // POS Operations
  POS_ACCESS: "pos.access",
  POS_DISCOUNT: "pos.discount",
  POS_REFUND: "pos.refund",
  POS_VOID: "pos.void",

  // Advanced
  AUDIT_LOGS: "audit.logs",
  SYSTEM_ADMIN: "system.admin",
} as const

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]

// Predefined role permissions
export const ROLE_PERMISSIONS = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ADMIN: [
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_EDIT,
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.PRODUCTS_CREATE,
    PERMISSIONS.PRODUCTS_EDIT,
    PERMISSIONS.PRODUCTS_MANAGE_STOCK,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_CREATE,
    PERMISSIONS.ORDERS_EDIT,
    PERMISSIONS.ORDERS_REFUND,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_EDIT,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.INVENTORY_RECEIVE,
    PERMISSIONS.INVENTORY_CHECK,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_EDIT,
    PERMISSIONS.POS_ACCESS,
    PERMISSIONS.POS_DISCOUNT,
    PERMISSIONS.POS_REFUND,
  ],
  MANAGER: [
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.PRODUCTS_EDIT,
    PERMISSIONS.PRODUCTS_MANAGE_STOCK,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_CREATE,
    PERMISSIONS.ORDERS_EDIT,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_EDIT,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.INVENTORY_RECEIVE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.POS_ACCESS,
    PERMISSIONS.POS_DISCOUNT,
  ],
  CASHIER: [
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_CREATE,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.POS_ACCESS,
  ],
  STAFF: [
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.POS_ACCESS,
  ],
} as const

// Route permissions mapping
export const ROUTE_PERMISSIONS = {
  "/settings/staff": [PERMISSIONS.USERS_VIEW],
  "/settings": [PERMISSIONS.SETTINGS_VIEW],
  "/products": [PERMISSIONS.PRODUCTS_VIEW],
  "/orders": [PERMISSIONS.ORDERS_VIEW],
  "/customers": [PERMISSIONS.CUSTOMERS_VIEW],
  "/inventory": [PERMISSIONS.INVENTORY_VIEW],
  "/reports": [PERMISSIONS.REPORTS_VIEW],
  "/pos": [PERMISSIONS.POS_ACCESS],
  "/posmobile": [PERMISSIONS.POS_ACCESS],
} as const

// Mapping between database permissions and permission constants
export const DATABASE_PERMISSION_MAPPING = {
  // Legacy database permissions mapping to new permission constants
  pos: [PERMISSIONS.POS_ACCESS, PERMISSIONS.POS_DISCOUNT, PERMISSIONS.POS_REFUND, PERMISSIONS.POS_VOID],
  customers_basic: [PERMISSIONS.CUSTOMERS_VIEW, PERMISSIONS.CUSTOMERS_CREATE],
  customers_full: [
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_EDIT,
    PERMISSIONS.CUSTOMERS_DELETE,
  ],
  products_basic: [PERMISSIONS.PRODUCTS_VIEW],
  products_full: [
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.PRODUCTS_CREATE,
    PERMISSIONS.PRODUCTS_EDIT,
    PERMISSIONS.PRODUCTS_DELETE,
    PERMISSIONS.PRODUCTS_MANAGE_STOCK,
  ],
  orders_basic: [PERMISSIONS.ORDERS_VIEW, PERMISSIONS.ORDERS_CREATE],
  orders_full: [
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_CREATE,
    PERMISSIONS.ORDERS_EDIT,
    PERMISSIONS.ORDERS_DELETE,
    PERMISSIONS.ORDERS_REFUND,
  ],
  inventory_basic: [PERMISSIONS.INVENTORY_VIEW],
  inventory_full: [
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.INVENTORY_RECEIVE,
    PERMISSIONS.INVENTORY_CHECK,
  ],
  reports: [PERMISSIONS.REPORTS_VIEW, PERMISSIONS.REPORTS_EXPORT],
  settings: [PERMISSIONS.SETTINGS_VIEW, PERMISSIONS.SETTINGS_EDIT],
  admin: Object.values(PERMISSIONS),
  all: Object.values(PERMISSIONS),
} as const
